FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# DoctorMap API

## Users Collection [/users]

### Get user info [GET]

+ Request (application/json)

        {
            "id": "9",
        }

+ Response 200 (application/json)

            {
                "id": "9",
                "phone": "+380681234567"
                "name": "Test User",
                "birthdate": "1990-01-01"
                "gender": "testuser@gmail.com",
                "city": "Запорожье",
                "access_token": "123123123",
            }

## User Registration [/users/register]

### Register new user [POST]

+ Request (application/json)

        {
            "phone": "+380681234567"
            "name": "New User",
            "birthdate": "1980-01-01"
            "gender": "newuser@gmail.com",
            "city": "Запорожье"
        }

+ Response 200 (application/json)

        {
            "id": 123,
            "phone": "+380681234567"
            "name": "New User",
            "birthdate": "1980-01-01"
            "gender": "newuser@gmail.com",
            "city": "Запорожье",
            "access_token": "123123123",
        }